### ISSUE TITLE
Lift is not working.

### ISSUE THREAD

**Issue by KrishnaPhalgun5168** [IIITBangalore/ticketsystemdemo#6]
#### Please choose an issue

- [ ] Water leakage
- [ ] Power cut
- [X] Lift inoperational
- [ ] Other

**Comment by IMT2018038** [comment]
Oh okay. We are working on it.
________________________________
From: KrishnaPhalgun5168 ***@***.***>
Sent: Wednesday, December 8, 2021 4:05 PM
To: IIITBangalore/ticketsystemdemo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IIITBangalore/ticketsystemdemo] Lift is not working. (Issue #6)


Please choose an issue

  *    Water leakage
  *    Power cut
  *    Lift inoperational
  *    Other

**Comment by IMT2018038** [comment]
Done.
